<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>XYZ_shop.Web</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="CustomValidationAttributes\MaxPriceAttribute.cs" />
    <Content Include="CustomValidationAttributes\NoSpecialCharactersAttribute.cs" />
    <Content Include="CustomValidationAttributes\UniqueGameTitleAttribute.cs" />
    <Content Include="CustomValidationAttributes\ValidateImageUrlAttribute.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.25" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.25">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\XYZ-shop.Application\XYZ-shop.Application.csproj" />
    <ProjectReference Include="..\XYZ-shop.Domain\XYZ-shop.Domain.csproj" />
    <ProjectReference Include="..\XYZ-shop.Infrastructure\XYZ-shop.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\User\" />
  </ItemGroup>

</Project>
